apiVersion: v1
kind: Pod
metadata:
  name: %NAME%
spec:
  schedulerName: my-controller
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 80
    command: ["bin/sh"]
    args: ["-c", "sleep %SLEEP%; echo 'slept for %SLEEP% seconds'"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: %CPU%
  restartPolicy: Never
