apiVersion: v1
kind: Service
metadata:
  name: controller-svc
  namespace: dist-sched
spec:
  clusterIP: None
  selector:
    component: controller
    tier: control-plane
    name: my-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
