apiVersion: v1
kind: Service
metadata:
  name: controller-svc
  namespace: kube-system
spec:
  selector:
    component: controller
    tier: control-plane
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


