apiVersion: batch/v1
kind: Job
metadata:
  name: 'indexed-job'
spec:
  completions: 27
  parallelism: 27
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: 'worker'
        image: bash
        imagePullPolicy: IfNotPresent
        command:
        - "bash"
        - "-c"
        - |
          items=(14.0 12.0 7.0 12.0 8.0 13.0 13.0 7.0 5.0 12.0 7.0 6.0 6.0 10.0 10.0 15.0 13.0 11.0 10.0 7.0 10.0 12.0 7.0 11.0 12.0 3.0 8.0)
          sleep ${items[$JOB_COMPLETION_INDEX]}; echo "slept for ${items[$JOB_COMPLETION_INDEX]} seconds"
        volumeMounts:
        - mountPath: /input
          name: input
      volumes:
      - name: input
        emptyDir: {}
