apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-controller-deployment
  namespace: kube-system
  labels:
    tier: control-plane
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 9
  selector:
    matchLabels:
      component: controller
      tier: control-plane
  template:
    metadata:
      labels:
        component: controller
        tier: control-plane
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: NoSchedule
      serviceAccountName: my-controller
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
      - command:
        - ./ctl
        name: my-controller
        image: cuso4/my-ctl
        ports:
          - containerPort: 80
