apiVersion: v1
kind: Pod
metadata:
  name: my-controller
  namespace: dist-sched
  labels:
    component: controller
    tier: control-plane
    name: my-controller
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: NoSchedule
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  containers:
  - command:
    - ./ctl
    - -schednum=%REPLICAS%
    - -mode=%MODE%
    name: my-controller
    image: cuso4/my-ctl:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10
  
