apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler
  namespace: dist-sched
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: %REPLICAS%
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            component: scheduler
            tier: control-plane
            version: second
      containers:
      - command:
        - /usr/local/bin/kube-scheduler
        - -schednum=%REPLICAS%
        - -mode=%MODE%
        - -trace=trace.out
        # - -cpuprofile=sched.prof
        image: cuso4/my-sched:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2379
        livenessProbe:
          grpc:
            port: 2379
          initialDelaySeconds: 10
        name: my-scheduler
        resources:
          requests:
            cpu: "5m"
        securityContext:
          privileged: true
      restartPolicy: Always
      hostNetwork: false
      hostPID: false
