apiVersion: v1
kind: Service
metadata:
  name: scheduler-headless
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    component: scheduler
    tier: control-plane
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


