apiVersion: v1
kind: Service
metadata:
  name: scheduler-headless
  namespace: dist-sched
spec:
  clusterIP: None
  selector:
    component: scheduler
    tier: control-plane
    version: third
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


