apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    sleep: "{{ .Values.sleep }}"
spec:
  schedulerName: {{ .Values.schedulerName }}
  containers:
  - name: busybox
    image: busybox
    command: ["bin/sh"]
    args: ["-c", "sleep {{ .Values.sleep }}; echo 'slept for {{ .Values.sleep }} seconds'"]
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "{{ .Values.sleep }}m"
  restartPolicy: Never
